version: "3"

services:

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - .:/var/www/html:cached
    networks:
      - backend

  nginx:
    image: 'nginx:alpine'
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '8000:80'
    networks:
      - backend

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - mysql-database:/var/lib/mysql:delegated
    networks:
      - backend

volumes:
  mysql-database:
    driver: local

networks:

  backend:

  frontend: